// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBps4ydhyWohSbvx886RdbPaizkHpNCnKc',
    appId: '1:570802168161:web:12068af0f28fe408f46520',
    messagingSenderId: '570802168161',
    projectId: 'app-filmes-f48f4',
    authDomain: 'app-filmes-f48f4.firebaseapp.com',
    storageBucket: 'app-filmes-f48f4.firebasestorage.app',
    measurementId: 'G-Q1GXSSHSGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99nIM2kyrgxqSu8Kt1ml8teAFuuqx0bw',
    appId: '1:570802168161:android:132d8b1dbd84ceebf46520',
    messagingSenderId: '570802168161',
    projectId: 'app-filmes-f48f4',
    storageBucket: 'app-filmes-f48f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgExzDOhoIO9AYcfAZN0oRTza0yrSqCnc',
    appId: '1:570802168161:ios:15b5d84ba2362246f46520',
    messagingSenderId: '570802168161',
    projectId: 'app-filmes-f48f4',
    storageBucket: 'app-filmes-f48f4.firebasestorage.app',
    iosClientId: '570802168161-h9t45l0icvjudo8m6dun25og9qe0p93j.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgExzDOhoIO9AYcfAZN0oRTza0yrSqCnc',
    appId: '1:570802168161:ios:15b5d84ba2362246f46520',
    messagingSenderId: '570802168161',
    projectId: 'app-filmes-f48f4',
    storageBucket: 'app-filmes-f48f4.firebasestorage.app',
    iosClientId: '570802168161-h9t45l0icvjudo8m6dun25og9qe0p93j.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBps4ydhyWohSbvx886RdbPaizkHpNCnKc',
    appId: '1:570802168161:web:aa1f2df80cfe2bd1f46520',
    messagingSenderId: '570802168161',
    projectId: 'app-filmes-f48f4',
    authDomain: 'app-filmes-f48f4.firebaseapp.com',
    storageBucket: 'app-filmes-f48f4.firebasestorage.app',
    measurementId: 'G-NH98RLT067',
  );

}